// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCOSmUASLWUok2-1hiw1w0RusG_ntYkM',
    appId: '1:991760797503:web:5cd93e16b3689f8ed34d8a',
    messagingSenderId: '991760797503',
    projectId: 'exp8-test',
    authDomain: 'exp8-test.firebaseapp.com',
    storageBucket: 'exp8-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_J6IjCYI27E-qy3eqyy2l-8U03L-0rw',
    appId: '1:991760797503:android:60bd845a286f2752d34d8a',
    messagingSenderId: '991760797503',
    projectId: 'exp8-test',
    storageBucket: 'exp8-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vZc3_rSvElMZ-Iy-3nF240Baij1lL48',
    appId: '1:991760797503:ios:ab6bf948b496c847d34d8a',
    messagingSenderId: '991760797503',
    projectId: 'exp8-test',
    storageBucket: 'exp8-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication81',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4vZc3_rSvElMZ-Iy-3nF240Baij1lL48',
    appId: '1:991760797503:ios:ab6bf948b496c847d34d8a',
    messagingSenderId: '991760797503',
    projectId: 'exp8-test',
    storageBucket: 'exp8-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication81',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCOSmUASLWUok2-1hiw1w0RusG_ntYkM',
    appId: '1:991760797503:web:a1d943c1707035d8d34d8a',
    messagingSenderId: '991760797503',
    projectId: 'exp8-test',
    authDomain: 'exp8-test.firebaseapp.com',
    storageBucket: 'exp8-test.firebasestorage.app',
  );
}
