import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // <-- 1. ADD THIS IMPORT

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // 2. You MUST pass in the options generated by `flutterfire configure`
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MaterialApp(
    title: "Maths Formulae",
    home: SearchFormulaScreen(), // This screen focuses only on searching
  ));
}

class SearchFormulaScreen extends StatefulWidget {
  const SearchFormulaScreen({super.key});

  @override
  State<SearchFormulaScreen> createState() => _SearchFormulaScreenState();
}

class _SearchFormulaScreenState extends State<SearchFormulaScreen> {
  // Controller for the search text field
  final _searchController = TextEditingController();

  // Database instance, pointing to your "Formulae" collection
  // Make sure this name exactly matches your collection name in Firebase!
  final CollectionReference formulae =
      FirebaseFirestore.instance.collection("Formulae");

  // State variables to hold the search result
  Map<String, dynamic>? _searchResult;
  String _statusMessage = "Enter a formula name to search";

  // Async function to perform the search
  Future<void> _searchFormula() async {
    String searchTerm = _searchController.text.trim();
    if (searchTerm.isEmpty) {
      setState(() {
        _statusMessage = "Please enter a name to search";
        _searchResult = null;
      });
      return;
    }

    try {
      // ---
      // IMPORTANT: READ THIS!
      //
      // 1. FIRESTORE INDEX: This query (using .where()) requires a Firestore Index.
      //    - Run the app, try to search. It will fail.
      //    - Look in your DEBUG CONSOLE (not the app screen).
      //    - Find the error message with a long URL.
      //    - Click that URL. It will open Firebase and auto-create the index.
      //    - Wait 2-3 minutes, restart the app, and it will work.
      //
      // 2. CASE SENSITIVITY: This query is case-sensitive.
      //    - A search for "area" will NOT find "Area".
      //    - Your collection name "Formulae" is also case-sensitive.
      // ---
      final querySnapshot =
          await formulae.where('name', isEqualTo: searchTerm).get();

      if (querySnapshot.docs.isNotEmpty) {
        // Found a match
        setState(() {
          // Get the first match and store its data
          _searchResult =
              querySnapshot.docs.first.data() as Map<String, dynamic>;
          _statusMessage = ""; // Clear status message
        });
      } else {
        // No match found
        setState(() {
          _searchResult = null; // Clear previous results
          _statusMessage = "Formula not found";
        });
      }
    } catch (e) {
      setState(() {
        _searchResult = null;
        _statusMessage = "An error occurred: $e";
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Search Formulae"),
        backgroundColor: Colors.deepPurple,
      ),
      body: Container(
        padding: EdgeInsets.all(20),
        child: Column(
          children: [
            // Search input field
            TextFormField(
              controller: _searchController,
              decoration: InputDecoration(
                labelText: "Enter formula name to search",
                border: OutlineInputBorder(),
                suffixIcon: IconButton(
                    icon: Icon(Icons.clear),
                    onPressed: () {
                      _searchController.clear();
                      setState(() {
                        _searchResult = null;
                        _statusMessage = "Enter a formula name to search";
                      });
                    }),
              ),
            ),
            SizedBox(height: 15),

            // Search button
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.deepPurple,
                foregroundColor: Colors.white,
                minimumSize: Size(double.infinity, 50), // Make button wide
              ),
              onPressed: _searchFormula, // Triggers the search
              child: Text('Search'),
            ),
            SizedBox(height: 20),

            // --- Display Results Area ---
            Expanded(
              child: Container(
                width: double.infinity,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "Result:",
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                    SizedBox(height: 10),

                    // If a result is found, display it
                    if (_searchResult != null)
                      Card(
                        elevation: 3,
                        child: ListTile(
                          title: Text(
                            // Use null-aware operators as a safeguard
                            _searchResult!['name'] ?? 'No Name',
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 18,
                            ),
                          ),
                          subtitle: Text(
                            "Category: ${_searchResult!['category'] ?? 'N/A'}\nFormula: ${_searchResult!['formula'] ?? 'N/A'}",
                            style: TextStyle(fontSize: 16),
                          ),
                          isThreeLine: true,
                        ),
                      )
                    // Otherwise, display the status message (e.g., "Formula not found")
                    else
                      Text(
                        _statusMessage,
                        style: TextStyle(fontSize: 16, color: Colors.grey.shade700),
                      ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}